### ISSUE TITLE
Millorar el sistema de tasques

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#424]
Aquesta funcionalitat es divideix en les següents subtasques:

- [ ] Millores en la pantalla de tasques #366
- [ ] Juntar/relacionar el tema dels estats amb les tasques. #361 
- [ ] Data límit per les tasques #362
