### ISSUE TITLE
Millores al sistema de notificacions

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#425]
Aquesta funcionalitat es divideix en les següents subtasques:

- [x] Igualar comportament del NOTIB al enviar notificacions des de RIPEA #343
- [x] Millores referents a enviaments CIE #359
- [x] Comportament de propietats d'enviament de notificació #342 
- [x] Millores referents als enviaments de les notificacions electròniques #357 
- [x] Optimitzar enviament d'anexos en les notificacions #454
