### ISSUE TITLE
Depuració d'errors i millores als fluxos de firma

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#441]
S'han trobat diversos errors amb els fluxos de firma:

- [x] Error al crear flux de firmes #435 
- [x] Problemes per editar un flux de firmes existent #437 
- [x] No se puede enviar un documento a firmar con un flujo de firmas predefinido #438 
- [x] Tipus de flux de firma Simple: No results found #439 
- [x] Revisió de literals de fluxos de firma #443  
- [x] Mostrar desplegable amb fluxos de plantilla existents #444
- [x] Error amb Firma amb passarel·la #449 
- [x] Error al crear un tipus de document amb firma amb portafirmes #450 
- [x] Error AJAX: [0] abort al afegir responsables de firma #452 
- [ ] Error reading 'fitxerExtension' on type es.caib.ripea.core.api.dto.DocumentDto #463
