### ISSUE TITLE
Millores en la gestió de tipus d'expedients

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#646]
- [x] Filtrar per procediments comuns dins la gestió de tipus d'expedients #631
- [x] Afegir filtre de cerca per codi SIA en la gestió de tipus d'expedients #641
- [x] Afegir columna "Comú" al llistat de la gestió de tipus d'expedients #643
- [x] Afegir columna "Codi SIA" al llistat de la gestió de tipus d'expedients #644
- [x] Afegir columna "Sèrie documental" al llistat de la gestió de tipus d'expedients #645
- [x] Combinar botons de tipus de documents, Metadades, Estats, Tasques, Grups, i Permisos #647
- [x] Modificar l'etiqueta Codi del tipus d'expedient #653
