### ISSUE TITLE
Revisar metadades d'un document

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#686]
Èpica que inclou les següents issues relacionades amb les metadades d'un documentdins l'arxiu:

- [ ] Revisar metadada cod_clasificacio #685
- [ ] Afegir unitat temporal a certes metadades #684
- [ ] Revisar les metadades ENI a mostrar #683
- [ ] Revisar metadada eni:app_tramite_doc #682
- [ ] Afegir descripció als valors de les metadades d'un document #681
- [ ] Revisar metadada eni:fecha_sellado #679
- [ ] Revisar camp CSV a la pipella firmes de la informació d el'arxiu d'un document #678
- [ ] Afegir el camp "Tipus de firma" a la informació de l'arxiu per a un document #677
- [ ] Eliminar camp "Format extensió" de la informació de l'arxiu per a un document #676
